-- Create application
CREATE APPLICATION AFRICAN_COMPANIES_ESTIMATOR
  FROM APPLICATION PACKAGE AFRICAN_COMPANIES_PACKAGE
  USING VERSION 1.0;

-- Create tables
CREATE OR REPLACE TABLE COMPANIES (
    NAME STRING,
    SECTOR STRING,
    EMPLOYEES INTEGER,
    YEARS_ESTABLISHED INTEGER,
    CAPEX FLOAT,
    MARKET_SHARE_ESTIMATE FLOAT,
    REVENUE FLOAT,
    REVENUE_SOURCE STRING,
    CONFIDENCE STRING
);

-- Create stored procedures
CREATE OR REPLACE PROCEDURE ESTIMATE_REVENUE()
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
HANDLER = 'estimate_revenue'
AS $$
def estimate_revenue(session):
    # Your estimation logic here
    return "Revenue estimation completed"
$$;